config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :events do
    post :publish, on: :member
    resources :comments do
      post :publish, on: :member
    end
  end
  root "home#index"

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  event_id   :integer
#  body       :string
#  tweet_url  :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  alias_attribute :text, :body

  def hashtag
    event.hashtag
  end

  def tweet_message
    "##{self.hashtag} #{self.body} #{Rails.application.routes.url_helpers.event_comment_url(self.event, self)}"
  end
end

app/controllers/comments_controller.rb
# Kontroler zarządzający komentarzami
class CommentsController < ApplicationController
  before_action :set_comment, only: [:publish, :show, :edit, :update, :destroy]
  before_action :set_event
  authorize_resource

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @event.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @event.comments.build(comment_params.merge(user: current_user))
    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@event, @comment], notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /events/1/comments/2/publish
  # 
  # Publikuje komentarz o podanym id na twitterze
  def publish
    twitter_client.update(@comment.tweet_message)
    flash[:notice] = "Event was successfully published to twitter"
    redirect_to :back
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_event
      @event = Event.find(params[:event_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params[:comment].permit(:body)
    end
end

app/views/comments/_comment.html.erb
<p><%= comment.text %> <%= link_to "Tweet!", publish_event_comment_path(@event, comment), method: :post %></p> 

app/views/comments/_form.html.erb
<%= form_for([@comment.event, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div><%= f.label :body %><br />
  <%= f.text_field :body %></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', [@event, comment] %></td>
        <td><%= link_to 'Edit', edit_event_comment_path(@event, comment) %></td>
        <td><%= link_to 'Destroy', [@event,comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_event_comment_path(@event) %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', event_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>
<p><%= @comment.body %></p>
<%= link_to 'Edit', edit_event_comment_path(@event, @comment) %> |
<%= link_to 'Back', event_comments_path(@event) %>