config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :events do
    post :publish, on: :member
    resources :comments do
      post :publish, on: :member
    end
  end
  root "home#index"

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  city        :string
#  hashtag     :string
#  date        :datetime
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Event < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  def tweet_message
    "Wydarzenie: #{name}, zobacz na: #{Rails.application.routes.url_helpers.event_url(self)}"
  end
  
end

app/controllers/events_controller.rb
# Kontroler wydarzeń, odpowiada na RestFULLowe akcję + publish
class EventsController < ApplicationController
  before_action :set_event, only: [:publish, :show, :edit, :update, :destroy]
  authorize_resource

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  # Wyświetla wydarzenie o podanym id, razem z jego komentarzami w systemie oraz tymi z twittera
  def show
    # binding.pry
    @comments = twitter_client.search("#agh_tai ##{@event.hashtag}").to_a + @event.comments
    @comments = @comments.sort_by(&:created_at)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /events/1/publish
  #
  # Publikuje wydarzenie o podanym id na twitterze
  def publish
    @event.tweet_message
    twitter_client.update(@event.tweet_message)
    flash[:notice] = "Event was successfully published to twitter"
    redirect_to :back
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :hashtag)
    end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div><%= f.label :hashtag %><br />
  <%= f.text_field :hashtag %></div>

  <div><%= f.label :name %><br />
  <%= f.text_field :name %></div>

  <div><%= f.label :description %><br />
  <%= f.text_field :description %></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Nazwa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<h3><%= @event.name %></h3>
<p><%= @event.description %></br>
#<%= @event.hashtag %></br></br>
<%= link_to "Publikuj na twitterze!", publish_event_path(@event), method: :post %>

<p> Komentarze: </p>
<%= render partial: "comments/comment", collection: @comments %>
<%= link_to 'Dodaj Komentarz', new_event_comment_path(@event) %> |
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>